# Database & Auth
JWT_SECRET=d7393b0046e2a4b4fe0c65c96c95d00b22c6ec58e4d9ecaebc6476b9a5534d2c
DB_PASSWORD=npg_WGjbaQIi3d0o

# Supabase Storage
SUPABASE_KEY=sb_secret_iDXHbM_Ib_r9H8dm6DCFNA_VkRQgyiS

# Stripe Payments
STRIPE_SECRET_KEY=sk_test_51TD60KElC7A7VDHuK01ygEGsag2ToqDieOLxXx2p9bbStWB19xWwbAEtGorbmLrZJWt9t5FwbpFiWrgMFL5m09Tb00hBa3vhVu
STRIPE_WEBHOOK_SECRET=whsec_85239ad4d89062aa97582c9c8920244dd6bd98e2e1bb0f38be58904a9ed84a47