spring.application.name=landapp
spring.profiles.include=secrets

security.jwt.secret-key=${JWT_SECRET}
# 1h in millisecond
security.jwt.expiration-time=3600000

# 1. Your Neon PostgreSQL connection URL
spring.datasource.url=jdbc:postgresql://ep-solitary-band-a1yx18oy-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=${DB_PASSWORD}

# 2. THE MAGIC LINE FOR CHANGING MODELS!
# "update" tells Spring to automatically modify the database tables when you change your Java code.
spring.jpa.hibernate.ddl-auto=create

# 3. Tells Spring which SQL dialect to use
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Supabase storage bucket to store images
supabase.url=https://xfavmtwxkeoznqisfklw.supabase.co
supabase.key=${SUPABASE_KEY}
supabase.bucket.name=land-listings

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

stripe.secret.key=${STRIPE_SECRET_KEY}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

# Redis Configuration
spring.data.redis.host=localhost
spring.data.redis.port=6379
# Expire cached data after 60 minutes (in milliseconds)
spring.cache.redis.time-to-live=3600000
