package com.example.landapp.entity;

import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import java.time.LocalDateTime;

@Entity

/*Specifies the exact name of the table in the database*/
@Table(name = "users")

/**/
@Inheritance(strategy = InheritanceType.JOINED)
@Data
public abstract class BaseUser {

    //marks the primary key of the data model
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY//meaning the value is generated by the system
    private Long id;

    private String firstName;
    private String lastName;

    @Column(unique = true, nullable = false)//provide extra metaData for the column .
    private String email;

    private String contactNumber;

    @Column(nullable = false)
    private String passwordHash;

    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;

    @UpdateTimestamp
    private LocalDateTime updatedAt;
}